<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-HRAE54G" ignored="0" name="Command line test" tests="3" failures="1" timestamp="21 May 2022 20:14:21 GMT" time="20.607" errors="0">
  <testcase name="X" time="0.002" classname="scripts._01_AppleTest">
    <failure type="java.lang.AssertionError" message="Failure on purpose">
      <![CDATA[java.lang.AssertionError: Failure on purpose
at scripts._01_AppleTest.X(_01_AppleTest.java:52)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- X -->
  <testcase name="testAppleTitle" time="1.366" classname="scripts._01_AppleTest"/>
  <testcase name="testAppleURL" time="1.374" classname="scripts._01_AppleTest"/>
</testsuite> <!-- Command line test -->
